library(plumber)
library(promises)
library(future)
library(openssl)
library(jose)
library(dplyr)
future::plan("multisession")

pr("plumber.R") %>% pr_run(host='0.0.0.0', port = 8000)
#pr("debug.R") %>% pr_run(host='0.0.0.0', port = 8001)
