apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster-test
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  labels:
    tier: backend
  image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
  # add a mount from <hostPath> on the host to on the node
  extraMounts:
  - hostPath: V:/vm-data/extra_mounts/data
    containerPath: /files
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    # propagation: HostToContainer
- role: worker
  labels:
    tier: database
  image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
  extraPortMappings:
  - containerPort: 30011
    hostPort: 6432
    listenAddress: "0.0.0.0"
    protocol: TCP
  # add a mount from <hostPath> on the host to on the node
  extraMounts:
  - hostPath: V:/vm-data/extra_mounts/db
    containerPath: /mnt/data
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    # propagation: Bidirectional
