apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

#NAME              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
#postgres-volume   1Gi        RWX            Retain           Available           manual                  16s
