apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pg-deploy
  name: pg-deploy-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30011
  selector:
    app: pg-deploy
  type: NodePort
status:
  loadBalancer: {}
